- name: "This is for docker install in slave node"
  hosts: ip-172-31-47-204
  tasks:
  - name: Install docker.
    package:
      name: docker
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
